version: "3.9"

services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wpp_db
      MYSQL_USER: wpp_user
      MYSQL_PASSWORD: wpp_pass
    volumes:
      - db_data:/var/lib/mysql

  wpp-db-server:
    build: ./wpp-db-server
    depends_on: [db]

  wpp-webhook:
    build: ./wpp-webhook

    build: ./wpp-frontend
    depends_on: [wpp-db-server]

volumes:
  db_data:


  wppconnect-server:
    image: ghcr.io/wppconnect-team/wppconnect-server:latest
    container_name: wppconnect-server
    restart: unless-stopped
    ports:
      - "21465:21465"
    volumes:
      - tokens:/usr/src/app/tokens
      - userdata:/usr/src/app/userDataDir
    depends_on: [wpp-db-server]

volumes:
  db_data:
  tokens:
  userdata:
