version: "3.9"

services:
  db:
    image: mysql:8.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wpp_db
      MYSQL_USER: wpp_user
      MYSQL_PASSWORD: wpp_pass
    volumes:
      - db_data:/var/lib/mysql
    networks: [backend]

  wpp-db-server:
    build: ./wpp-db-server
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: wpp_user
      DB_PASS: wpp_pass
      DB_NAME: wpp_db
      WPP_API_URL: http://wppconnect-server:21465
      WPP_SERVER_HOST=: http://wppconnect-server:21465
      WEBHOOK_URL=: http://wpp-webhook:3005/wpp-webhook
      HUB_BASE_URL: "http://69.62.98.33:3010"
      HUB_API_KEY:  "${HOSTNAME}"
      VPS_NAME: "${HOSTNAME}"
    depends_on:         # ← amplía
      - db
    ports:
      - "3001:3001"
    networks: [backend]

  ### ---- Emuladores Android -----------------

  wpp-webhook:
    build: ./wpp-webhook
    restart: unless-stopped
    depends_on: [wpp-db-server]
    ports:
      - "3005:3005"
    networks: [backend]

  wppconnect-server:

    build: ./wppconnect-server

    container_name: wppconnect-server

    restart: unless-stopped

    depends_on: [wpp-db-server]

    ports:

      - "21465:21465"

    volumes:

      - tokens:/usr/src/app/tokens

      - userdata:/usr/src/app/userDataDir

    networks: [backend]

  frontend:
    build: ./wpp-frontend
    restart: unless-stopped
    depends_on: [wpp-db-server]
    ports:
      - "3000:80"
    networks:
    - frontend      # <- ya estaba
    - backend       # <- AÑADIR

networks:
  backend:
  frontend:

volumes:
  db_data:
  tokens:
  userdata:
  droid1_data:
  droid2_data:
  droid3_data:
